"""add subscription_plan to raw_events

Revision ID: 1f9243cb48b3
Revises: 6f4fadaf1f31
Create Date: 2026-01-08 06:11:43.659525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9243cb48b3'
down_revision: Union[str, Sequence[str], None] = '6f4fadaf1f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_events', sa.Column('subscription_plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_events', 'subscription_plan')
    # ### end Alembic commands ###
