"""Initial migration

Revision ID: 6f4fadaf1f31
Revises: 
Create Date: 2026-01-08 05:57:17.878373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4fadaf1f31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregate_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_enqueued', sa.Integer(), nullable=True),
    sa.Column('total_processed', sa.Integer(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.Column('low_risk_count', sa.Integer(), nullable=True),
    sa.Column('medium_risk_count', sa.Integer(), nullable=True),
    sa.Column('high_risk_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregate_stats_id'), 'aggregate_stats', ['id'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_processed_events_id'), 'processed_events', ['id'], unique=False)
    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('is_eu', sa.Boolean(), nullable=True),
    sa.Column('has_consent', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_content_id'), 'raw_events', ['content_id'], unique=False)
    op.create_index(op.f('ix_raw_events_device_id'), 'raw_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_raw_events_event_id'), 'raw_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_raw_events_id'), 'raw_events', ['id'], unique=False)
    op.create_index(op.f('ix_raw_events_user_id'), 'raw_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_events_user_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_event_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_device_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_content_id'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index(op.f('ix_processed_events_id'), table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_aggregate_stats_id'), table_name='aggregate_stats')
    op.drop_table('aggregate_stats')
    # ### end Alembic commands ###
